# Generated by Django 5.2.7 on 2026-03-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_partnerships', '0007_coursecreator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='center',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='partner',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
